version: "3.6"

# Launch develop-env for LSST_DDS_DOMAIN_ID=7. This is to support work outside
# the normal domain=0.
# ospl-azar2 - azar2.cp.lsst.org

services:

  develop-env-domain-007:
    image: ts-dockerhub.lsst.org/develop-env:c0021.000
    container_name: develop-env-domain-007
    environment:
      - LSST_DDS_DOMAIN_NAME=ospl_sp_ddsi_7
      - LSST_DDS_DOMAIN_ID=7
      - LSST_DDS_PARTITION_PREFIX=summit
      - OSPL_INFOFILE=/tmp/ospl-info-develop.log
      - OSPL_ERRORFILE=/tmp/ospl-error-develop.log
    volumes:
      - ${OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${OSPL_SHMEM_DEBUG_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
