version: "3.6"

services:

  genericcamera101:
    image: ts-dockerhub.lsst.org/genericcamera-vimba:${CYCLE}
    container_name: genericcamera101
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_SITE=summit
      - LSST_DDS_INTERFACE=??
      - RUN_ARG=101
      - OSPL_INFOFILE=/tmp/ospl-info-gc101.log
      - OSPL_ERRORFILE=/tmp/ospl-error-gc101.log
    volumes:
      - ${OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.17X.XX"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  genericcamera102:
    image: ts-dockerhub.lsst.org/genericcamera-vimba:${CYCLE}
    container_name: genericcamera102
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_SITE=summit
      - LSST_DDS_INTERFACE=??
      - RUN_ARG=102
      - OSPL_INFOFILE=/tmp/ospl-info-gc102.log
      - OSPL_ERRORFILE=/tmp/ospl-error-gc102.log
    volumes:
      - ${OSPL_SHMEM_SOCKET_DIR}:/tmp/
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    ipc: host
    pid: host
    networks:
      dds-network:
        ipv4_address: "139.229.17X.XX"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"


networks:
  default:
    external:
      name: dds-network
  dds-network:
    external: true
