# Using this file requires the following environment files
# - setup.env
# - setup_kp.env

version: '3.6'

services:

  salkafka-auxtel:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_AUXTEL}
    container_name: salkafka-auxtel
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_AUXTEL}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=ATDome ATDomeTrajectory ATAOS ATPneumatics ATHexapod ATPtg ATMCS
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.240"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-comcam:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_COMCAM}
    container_name: salkafka-comcam
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_COMCAM}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=CCHeaderService CCArchiver CCCamera
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.241"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-m1m3:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_M1M3}
    container_name: salkafka-m1m3
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_M1M3}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - REPLICATION=3
      - PARTITIONS=1
      - WAIT_ACK=1
      - CSC_LIST=--file m1m3.yaml
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.242"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-m2:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_M2}
    container_name: salkafka-m2
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_M2}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=MTRotator MTHexapod MTM2 MTMount Script
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.243"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-latiss:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_LATISS}
    container_name: salkafka-latiss
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_LATISS}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=ATArchiver ATCamera ATHeaderService ATSpectrograph
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.244"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-maintel:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_MAINTEL}
    container_name: salkafka-maintel
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_MAINTEL}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=MTAOS MTDome MTDomeTrajectory MTPtg
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.245"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-mtmount:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_MTMOUNT}
    container_name: salkafka-mtmount
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_MTMOUNT}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=MTMount
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.246"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-obssys:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_OBSSYS}
    container_name: salkafka-obssys
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_OBSSYS}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=GenericCamera Scheduler Script ScriptQueue Watcher
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.247"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-test:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_TEST}
    container_name: salkafka-test
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_ID=${DOMAINID_TEST}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=Test
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.248"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  salkafka-eas:
    image: ts-dockerhub.lsst.org/salkafka:${CYCLE_EAS}
    container_name: salkafka-eas
    environment:
      - LSST_DDS_PARTITION_PREFIX=summit
      - LSST_DDS_DOMAIN_NAME=ospl_sp_ddsi_${DOMAINID_EAS}
      - LSST_DDS_DOMAIN_ID=${DOMAINID_EAS}
      - BROKER_IP=kafka-0-summit-efd.lsst.codes
      - BROKER_PORT=31090
      - REGISTRY_ADDR=https://schema-registry-summit-efd.lsst.codes
      - LOG_LEVEL=20
      - PARTITIONS=1
      - WAIT_ACK=1
      - REPLICATION=3
      - CSC_LIST=DIMM DSM WeatherStation ESS HVAC
    stdin_open: true
    volumes:
      - startup.sh:/home/saluser/.startup.sh
      - ${TS_IDL_DIRECTORY}:/opt/lsst/software/stack/miniconda/lib/python3.7/idl
      - ${OSPL_SHMEM_CONFIG}:${OSPL_MOUNT_POINT}
    tty: true
    networks:
      dds-network:
        ipv4_address: "139.229.170.249"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  default:
    external:
      name: dds-network
  dds-network:
    external: true
